language: python
python:
  - "3.2"
# command to install dependencies
install: "pip install -r requirements-dev --use-mirrors"
# command to run tests, e.g. python setup.py test
script:
  - cd src/pyherc
  - nosetests --with-coverage --cover-package=pyherc
after_success:
  - coveralls
