language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests, e.g. python setup.py test
script:
  - cd src/pyherc
  - nosetests --with-coverage --cover-package=pyherc
after_success:
  - coveralls --config_file .coveragerc
